### PR TITLE
1.19.3 Update

### PR DESCRIPTION
**Pull request by JustLetterV**

### CODE REVIEW

**Comment by ruvaldak** [comment]
Does this run on pre-1.19.3 versions of MC when compiled? I try to make sure that this mod runs on multiple MC versions from a single jar.

**Comment by JustLetterV** [comment]
No, this only runs with 1.19.3 and possibly future versions. Sadly Mojang changed the math library they are using, that's why.

**Comment by ruvaldak** [comment]
I see. That's very unfortunate. Hmm. Do I even need to import that math library? Like, I know a matrix is being called for in the drawTextureQuad function's parameters, but do I need an import for that?

**Comment by JustLetterV** [comment]
Yes, you need to import Matrix4f.

**Comment by ruvaldak** [comment]
Blech. That's unfortunate. Thanks for the PR, I'll merge it and push an update to Modrinth and CF.

**Pull request merged**
